import 'package:dart_code_linter/src/analyzers/lint_analyzer/models/severity.dart';
import 'package:dart_code_linter/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/prefer_first_or_null_rule.dart';
import 'package:test/test.dart';

import '../../../../../helpers/rule_test_helper.dart';

const _examplePath = 'prefer_first_or_null/examples/example.dart';

void main() {
  group(
    'PreferFirstOrNullRule',
    () {
      test('initialization', () async {
        final unit = await RuleTestHelper.resolveFromFile(_examplePath);
        final issues = PreferFirstOrNullRule().check(unit);

        RuleTestHelper.verifyInitialization(
          issues: issues,
          ruleId: PreferFirstOrNullRule.ruleId,
          severity: Severity.style,
        );
      });

      test('reports about found issues', () async {
        final unit = await RuleTestHelper.resolveFromFile(_examplePath);
        final issues = PreferFirstOrNullRule().check(unit);

        RuleTestHelper.verifyIssues(
          issues: issues,
          startLines: [
            10,
            12,
            18,
            25,
            27,
            28,
            35,
            38,
            44,
            50,
            56,
            58,
            64,
            71,
            74,
            80,
            87,
            89,
            95,
            102,
            104,
            110,
            117,
            119,
            125,
            132,
            134,
            140,
            147,
            149,
            155,
            162,
            165,
            166,
            174,
            177,
            184,
            187,
            193,
          ],
          startColumns: [
            27,
            34,
            5,
            23,
            31,
            31,
            5,
            5,
            9,
            5,
            22,
            29,
            5,
            36,
            7,
            5,
            26,
            33,
            5,
            32,
            39,
            5,
            28,
            35,
            5,
            24,
            31,
            5,
            31,
            38,
            5,
            39,
            7,
            47,
            5,
            5,
            38,
            7,
            5,
          ],
          messages: [
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
            PreferFirstOrNullRule.warningMessage,
          ],
          replacementComments: [
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
            PreferFirstOrNullRule.replaceComment,
          ],
          replacements: [
            'iterable.firstOrNull',
            'iterable.firstOrNull',
            '..firstOrNull',
            'list.firstOrNull',
            'list.firstOrNull',
            'list.firstOrNull',
            '..firstOrNull',
            '..firstOrNull',
            '..firstOrNull',
            '..firstOrNull',
            'set.firstOrNull',
            'set.firstOrNull',
            '..firstOrNull',
            'doubleLinkedQueue.firstOrNull',
            'doubleLinkedQueue.firstOrNull',
            '..firstOrNull',
            'hashSet.firstOrNull',
            'hashSet.firstOrNull',
            '..firstOrNull',
            'linkedHashSet.firstOrNull',
            'linkedHashSet.firstOrNull',
            '..firstOrNull',
            'listQueue.firstOrNull',
            'listQueue.firstOrNull',
            '..firstOrNull',
            'queue.firstOrNull',
            'queue.firstOrNull',
            '..firstOrNull',
            'splayTreeSet.firstOrNull',
            'splayTreeSet.firstOrNull',
            '..firstOrNull',
            'unmodifiableListView.firstOrNull',
            'unmodifiableListView.firstOrNull',
            'unmodifiableListView.firstOrNull',
            '..firstOrNull',
            '..firstOrNull',
            'unmodifiableSetView.firstOrNull',
            'unmodifiableSetView.firstOrNull',
            '..firstOrNull',
          ],
          locationTexts: [
            'iterable.first',
            'iterable.elementAt(0)',
            '..elementAt(0)',
            'list.first',
            'list.elementAt(0)',
            'list[0]',
            '..elementAt(0)',
            '..[0]',
            '..[0]',
            '..[0]',
            'set.first',
            'set.elementAt(0)',
            '..elementAt(0)',
            'doubleLinkedQueue.first',
            'doubleLinkedQueue.elementAt(0)',
            '..elementAt(0)',
            'hashSet.first',
            'hashSet.elementAt(0)',
            '..elementAt(0)',
            'linkedHashSet.first',
            'linkedHashSet.elementAt(0)',
            '..elementAt(0)',
            'listQueue.first',
            'listQueue.elementAt(0)',
            '..elementAt(0)',
            'queue.first',
            'queue.elementAt(0)',
            '..elementAt(0)',
            'splayTreeSet.first',
            'splayTreeSet.elementAt(0)',
            '..elementAt(0)',
            'unmodifiableListView.first',
            'unmodifiableListView.elementAt(0)',
            'unmodifiableListView[0]',
            '..elementAt(0)',
            '..[0]',
            'unmodifiableSetView.first',
            'unmodifiableSetView.elementAt(0)',
            '..elementAt(0)',
          ],
        );
      });
    },
  );
}
